### ISSUE TITLE
Artigo já inserido em uma publicação

### ISSUE THREAD

**Issue by brunopulis** [devtranslate/medium#4]
@larismourullo Eu acredito que o Medium não permita incluir um post em mais de uma publicação, tenho dois artigos traduzidos em uma publicação minha e gostaria de incluir ele no projeto. Sabe me dizer algo sobre isso?

**Comment by larismourullo** [comment]
Pelo que observo só é possível mesmo incluir em apenas uma publicação, a não ser que você "republique" ele em outra. Nesse caso basta incluir este artigo diretamente na api ou qualquer coisa me informar que posso incluir também.
