### ISSUE TITLE
Mudar o link de GitHub para como contribuir

### ISSUE THREAD

**Issue by woliveiras** [devtranslate/medium#5]
Pessoal, algo que fez aumentar a quantidade de gente nos procurando para enviar artigos na nossa publicação foi mudar de "sobre nos" para "como publicar aqui" no nosso menu de navegação na publicação.

![selection_113](https://user-images.githubusercontent.com/4243601/36721605-241ce40a-1b8a-11e8-8620-de6dddb5a29c.png)

No nosso caso é um artigo (http://bit.ly/contribuindo-com-o-TC), mas poderia até ser um documento aqui neste repo ensinando a pessoa a contribuir com o projeto.

O que acham?

**Comment by larismourullo** [comment]
Podemos melhorar o READ.me (acrescentar mais informações) e utiliza-lo para este fim 💃

**Comment by woliveiras** [comment]
Sucesso, @larismourullo 

Prefere fechar a issue ou manter aberta pra lembrar da atualização?

**Comment by larismourullo** [comment]
@woliveiras  Já fiz a alteração no medium, preciso só adicionar uma informação extra no READ.me, mas já ta anotado. Vou fechar a issue, obrigada pela dica 👍
